
from pathlib import Path
import numpy as np

# Writes a binary little endian PLY
def WriteBinaryPly(path, points, colors, faces = None):
    path = Path(path)

    points = np.asarray(points, dtype = np.float32)
    colors = np.asarray(colors)

    if faces is None:
        faces = []

    faces = np.asarray(faces, dtype = np.int32)

    if points.ndim != 2 or points.shape[1] != 3:
        raise ValueError("points must be shaped (N, 3)")

    if colors.ndim != 2 or colors.shape[1] < 3:
        raise ValueError("colors must be shaped (N, 3) or (N, 4)")

    colors = colors[:, :3]

    if colors.dtype != np.uint8:
        colors = np.clip(colors, 0, 255).astype(np.uint8)

    if len(points) != len(colors):
        raise ValueError("points and colors must have the same length")

    if faces.size > 0:
        if faces.ndim != 2 or faces.shape[1] != 3:
            raise ValueError("faces must be shaped (M, 3)")

        if faces.min() < 0 or faces.max() >= len(points):
            raise ValueError("faces contain invalid vertex indices")
    else:
        faces = np.empty((0, 3), dtype = np.int32)

    vertexCount = len(points)
    faceCount = len(faces)

    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        f"element vertex {vertexCount}\n"
        "property float x\n"
        "property float y\n"
        "property float z\n"
        "property uchar red\n"
        "property uchar green\n"
        "property uchar blue\n"
        f"element face {faceCount}\n"
        "property list uchar int vertex_indices\n"
        "end_header\n"
    ).encode("ascii")

    vertexData = np.empty(
        vertexCount,
        dtype = [
            ("x", "<f4"),
            ("y", "<f4"),
            ("z", "<f4"),
            ("red", "u1"),
            ("green", "u1"),
            ("blue", "u1"),
        ]
    )

    vertexData["x"] = points[:, 0]
    vertexData["y"] = points[:, 1]
    vertexData["z"] = points[:, 2]
    vertexData["red"] = colors[:, 0]
    vertexData["green"] = colors[:, 1]
    vertexData["blue"] = colors[:, 2]

    faceData = np.empty(
        faceCount,
        dtype = [
            ("vertexCount", "u1"),
            ("v0", "<i4"),
            ("v1", "<i4"),
            ("v2", "<i4"),
        ]
    )

    if faceCount > 0:
        faceData["vertexCount"] = 3
        faceData["v0"] = faces[:, 0]
        faceData["v1"] = faces[:, 1]
        faceData["v2"] = faces[:, 2]

    with open(path, "wb") as file:
        file.write(header)
        vertexData.tofile(file)
        faceData.tofile(file)

# Writes an OBJ with vertices, UVs, and triangular faces
def WriteOBJ(path, points, uvs, faces = None):
    path = Path(path)

    points = np.asarray(points, dtype = np.float32)
    uvs = np.asarray(uvs, dtype = np.float32)

    if faces is None:
        faces = []

    faces = np.asarray(faces, dtype = np.int32)

    if points.ndim != 2 or points.shape[1] != 3:
        raise ValueError("points must be shaped (N, 3)")

    if uvs.ndim != 2 or uvs.shape[1] != 2:
        raise ValueError("uvs must be shaped (N, 2)")

    if len(points) != len(uvs):
        raise ValueError("points and uvs must have the same length")

    if faces.size > 0:
        if faces.ndim != 2 or faces.shape[1] != 3:
            raise ValueError("faces must be shaped (M, 3)")

        if faces.min() < 0 or faces.max() >= len(points):
            raise ValueError("faces contain invalid vertex indices")
    else:
        faces = np.empty((0, 3), dtype = np.int32)

    path.parent.mkdir(parents = True, exist_ok = True)

    with open(path, "w", newline = "\n") as file:
        name = path.stem

        file.write("# OBJ generated by depthToMesh.py\n")
        file.write(f"o {name}\n")
        file.write(f"usemtl {name}\n\n")

        for point in points:
            file.write(f"v {point[0]} {point[1]} {point[2]}\n")

        file.write("\n")

        for uv in uvs:
            file.write(f"vt {uv[0]} {uv[1]}\n")

        file.write("\n")

        for face in faces:
            a = face[0] + 1
            b = face[1] + 1
            c = face[2] + 1

            file.write(f"f {a}/{a} {b}/{b} {c}/{c}\n")